import type { Metadata } from 'next';

import Header from './_components/header/Header';
import { AuthProvider } from '@/app/admin/context/AuthContext';
import { EmployeesProvider } from './context/EmployeesContext';
import { PartnersProvider } from './context/PartnersContext';
import { BookingsProvider } from './context/BookingsContext';
import { ToursProvider } from './context/ToursContext';
import { GeneralProvider } from './context/GeneralContext';
import { CustomersProvider } from './context/CustomersContext';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function AdminLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className=''>
			<AuthProvider>
				<GeneralProvider>
					<ToursProvider>
						<BookingsProvider>
							<PartnersProvider>
								<EmployeesProvider>
									<CustomersProvider>
										<Header />

										<main className='flex items-center justify-center min-h-screen py-8 bg-slate-50 '>
											{children}
										</main>
									</CustomersProvider>
								</EmployeesProvider>
							</PartnersProvider>
						</BookingsProvider>
					</ToursProvider>
				</GeneralProvider>
			</AuthProvider>
		</div>
	);
}
