import type { Metadata } from 'next';
import 'bootstrap/dist/css/bootstrap.min.css';

import Header from './_components/header/Header';
import { AuthProvider } from '@/app/admin/context/authContext';
import { EmployeesProvider } from './context/EmployeesContext';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function AdminLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<AuthProvider>
					<EmployeesProvider>
						<header className='fixed w-full z-10'>
							<Header />
						</header>

						<main className='flex items-center justify-center min-h-screen'>
							{children}
						</main>
					</EmployeesProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
